//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.Inport = new HashSet<Inport>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int id { get; set; }
        public string goodsname { get; set; }
        public string produceplace { get; set; }
        public string size { get; set; }
        public int pressid { get; set; }
        public decimal price { get; set; }
        public int providerid { get; set; }
        public int number { get; set; }
        public int dangernum { get; set; }
        public string goodsimg { get; set; }
    
        public virtual Press Press { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<Inport> Inport { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
