//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inport
    {
        public int id { get; set; }
        public int providerid { get; set; }
        public string paytype { get; set; }
        public System.DateTime inporttime { get; set; }
        public string operateperson { get; set; }
        public int number { get; set; }
        public decimal inportprice { get; set; }
        public int goodsid { get; set; }
        public int userid { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
    }
}
