//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int noticeid { get; set; }
        public int userid { get; set; }
        public System.DateTime noticetime { get; set; }
        public string noticename { get; set; }
        public string noticecontent { get; set; }
    
        public virtual User User { get; set; }
    }
}
