//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Goods = new HashSet<Goods>();
            this.Inport = new HashSet<Inport>();
        }
    
        public int id { get; set; }
        public string providername { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string providerperson { get; set; }
        public string phone { get; set; }
        public string bank { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual ICollection<Inport> Inport { get; set; }
    }
}
