//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Department = new HashSet<Department>();
            this.Inport = new HashSet<Inport>();
            this.Sales = new HashSet<Sales>();
            this.Notice = new HashSet<Notice>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> roleid { get; set; }
        public System.DateTime usertime { get; set; }
    
        public virtual ICollection<Department> Department { get; set; }
        public virtual ICollection<Inport> Inport { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual ICollection<Notice> Notice { get; set; }
    }
}
